# Generated by Django 5.1 on 2024-08-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heyhey', '0002_remove_order_updated_at_category_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='address',
            field=models.TextField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='city',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='country',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='state',
            field=models.CharField(max_length=191),
        ),
    ]
