# Generated by Django 5.1 on 2024-08-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heyhey', '0003_alter_category_name_alter_industry_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
